name: latexmk paper
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: '${{ github.workspace }}/Texlivefile'
      - name: Prepare latexmk
        run: |
          updmap -sys
          texhash
          tlmgr generate language --rebuild-sys
          if [ ! -f "latexmkrc" ]; then
            cp "_latexmkrc" "latexmkrc"
          fi
      - run: latexmk paper
      - uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: |
            paper.pdf
  spell-checking:
    # This is based on https://github.com/mh61503891/action-paper-aspell/tree/master
    #
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      # Original action does not work well - see https://github.com/awalsh128/cache-apt-pkgs-action/pull/136
      # The action is not updated - and thus the dictionaries are not updated
      - uses: bscott-zebra/cache-apt-pkgs-action@bdb5bbaae8f11b3e4e63cf78e303ac1519dcff7f
        with:
          packages: aspell aspell-en
          version: 1.0
          execute_install_scripts: true

      - name: aspell
        run: |
          echo "| file | status |" >> $GITHUB_STEP_SUMMARY
          echo "| -- | -- |" >> $GITHUB_STEP_SUMMARY
          for tex in $(ls *.tex content/*.tex 2>/dev/null); do
            # One could add a personal dictionary using --personal=.aspell.en.pws
            words=$(aspell --mode=tex -l en_US --encoding=utf-8 --conf=./.aspell.conf -p ./.aspell.en.pws list < $tex | sort | uniq | tr '\n' ' ')
            if [ -z "$words" ]; then
              echo "| $tex | ✅ |" >> $GITHUB_STEP_SUMMARY
            else
              echo "| $tex | ❌ $words |" >> $GITHUB_STEP_SUMMARY
            fi
          done
